#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNS_IT_Ticketing_System_v1._0
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITTickets")]
	public partial class EquipReDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEquipmentReturn(EquipmentReturn instance);
    partial void UpdateEquipmentReturn(EquipmentReturn instance);
    partial void DeleteEquipmentReturn(EquipmentReturn instance);
    #endregion
		
		public EquipReDataContext() : 
				base(global::CNS_IT_Ticketing_System_v1._0.Properties.Settings.Default.ITTicketsConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public EquipReDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EquipReDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EquipReDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EquipReDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EquipmentReturn> EquipmentReturns
		{
			get
			{
				return this.GetTable<EquipmentReturn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EquipmentReturns")]
	public partial class EquipmentReturn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IDText;
		
		private string _FirstContactPerson;
		
		private string _SecondContactPerson;
		
		private string _ThirdContactperson;
		
		private System.Nullable<System.DateTime> _FirstContactDate;
		
		private System.Nullable<System.DateTime> _SecondContactDate;
		
		private System.Nullable<System.DateTime> _ThirdContactDate;
		
		private string _Notes;
		
		private System.Nullable<bool> _EscalationStatus;
		
		private string _EscalationAgent;
		
		private System.Nullable<System.DateTime> _EscalationDate;
		
		private string _Reason;
		
		private string _Ticketor;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _TagID;
		
		private System.Nullable<char> _TicketStatus;
		
		private System.Nullable<char> _Priority;
		
		private string _Phone_Number;
		
		private string _Assignee;
		
		private string _AdditionalNotes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIDTextChanging(string value);
    partial void OnIDTextChanged();
    partial void OnFirstContactPersonChanging(string value);
    partial void OnFirstContactPersonChanged();
    partial void OnSecondContactPersonChanging(string value);
    partial void OnSecondContactPersonChanged();
    partial void OnThirdContactpersonChanging(string value);
    partial void OnThirdContactpersonChanged();
    partial void OnFirstContactDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFirstContactDateChanged();
    partial void OnSecondContactDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSecondContactDateChanged();
    partial void OnThirdContactDateChanging(System.Nullable<System.DateTime> value);
    partial void OnThirdContactDateChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnEscalationStatusChanging(System.Nullable<bool> value);
    partial void OnEscalationStatusChanged();
    partial void OnEscalationAgentChanging(string value);
    partial void OnEscalationAgentChanged();
    partial void OnEscalationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEscalationDateChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnTicketorChanging(string value);
    partial void OnTicketorChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnTagIDChanging(string value);
    partial void OnTagIDChanged();
    partial void OnTicketStatusChanging(System.Nullable<char> value);
    partial void OnTicketStatusChanged();
    partial void OnPriorityChanging(System.Nullable<char> value);
    partial void OnPriorityChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnAssigneeChanging(string value);
    partial void OnAssigneeChanged();
    partial void OnAdditionalNotesChanging(string value);
    partial void OnAdditionalNotesChanged();
    #endregion
		
		public EquipmentReturn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDText", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string IDText
		{
			get
			{
				return this._IDText;
			}
			set
			{
				if ((this._IDText != value))
				{
					this.OnIDTextChanging(value);
					this.SendPropertyChanging();
					this._IDText = value;
					this.SendPropertyChanged("IDText");
					this.OnIDTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstContactPerson", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FirstContactPerson
		{
			get
			{
				return this._FirstContactPerson;
			}
			set
			{
				if ((this._FirstContactPerson != value))
				{
					this.OnFirstContactPersonChanging(value);
					this.SendPropertyChanging();
					this._FirstContactPerson = value;
					this.SendPropertyChanged("FirstContactPerson");
					this.OnFirstContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondContactPerson", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string SecondContactPerson
		{
			get
			{
				return this._SecondContactPerson;
			}
			set
			{
				if ((this._SecondContactPerson != value))
				{
					this.OnSecondContactPersonChanging(value);
					this.SendPropertyChanging();
					this._SecondContactPerson = value;
					this.SendPropertyChanged("SecondContactPerson");
					this.OnSecondContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdContactperson", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ThirdContactperson
		{
			get
			{
				return this._ThirdContactperson;
			}
			set
			{
				if ((this._ThirdContactperson != value))
				{
					this.OnThirdContactpersonChanging(value);
					this.SendPropertyChanging();
					this._ThirdContactperson = value;
					this.SendPropertyChanged("ThirdContactperson");
					this.OnThirdContactpersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstContactDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FirstContactDate
		{
			get
			{
				return this._FirstContactDate;
			}
			set
			{
				if ((this._FirstContactDate != value))
				{
					this.OnFirstContactDateChanging(value);
					this.SendPropertyChanging();
					this._FirstContactDate = value;
					this.SendPropertyChanged("FirstContactDate");
					this.OnFirstContactDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondContactDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SecondContactDate
		{
			get
			{
				return this._SecondContactDate;
			}
			set
			{
				if ((this._SecondContactDate != value))
				{
					this.OnSecondContactDateChanging(value);
					this.SendPropertyChanging();
					this._SecondContactDate = value;
					this.SendPropertyChanged("SecondContactDate");
					this.OnSecondContactDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdContactDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThirdContactDate
		{
			get
			{
				return this._ThirdContactDate;
			}
			set
			{
				if ((this._ThirdContactDate != value))
				{
					this.OnThirdContactDateChanging(value);
					this.SendPropertyChanging();
					this._ThirdContactDate = value;
					this.SendPropertyChanged("ThirdContactDate");
					this.OnThirdContactDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EscalationStatus", DbType="Bit")]
		public System.Nullable<bool> EscalationStatus
		{
			get
			{
				return this._EscalationStatus;
			}
			set
			{
				if ((this._EscalationStatus != value))
				{
					this.OnEscalationStatusChanging(value);
					this.SendPropertyChanging();
					this._EscalationStatus = value;
					this.SendPropertyChanged("EscalationStatus");
					this.OnEscalationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EscalationAgent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string EscalationAgent
		{
			get
			{
				return this._EscalationAgent;
			}
			set
			{
				if ((this._EscalationAgent != value))
				{
					this.OnEscalationAgentChanging(value);
					this.SendPropertyChanging();
					this._EscalationAgent = value;
					this.SendPropertyChanged("EscalationAgent");
					this.OnEscalationAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EscalationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EscalationDate
		{
			get
			{
				return this._EscalationDate;
			}
			set
			{
				if ((this._EscalationDate != value))
				{
					this.OnEscalationDateChanging(value);
					this.SendPropertyChanging();
					this._EscalationDate = value;
					this.SendPropertyChanged("EscalationDate");
					this.OnEscalationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticketor", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Ticketor
		{
			get
			{
				return this._Ticketor;
			}
			set
			{
				if ((this._Ticketor != value))
				{
					this.OnTicketorChanging(value);
					this.SendPropertyChanging();
					this._Ticketor = value;
					this.SendPropertyChanged("Ticketor");
					this.OnTicketorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagID", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TagID
		{
			get
			{
				return this._TagID;
			}
			set
			{
				if ((this._TagID != value))
				{
					this.OnTagIDChanging(value);
					this.SendPropertyChanging();
					this._TagID = value;
					this.SendPropertyChanged("TagID");
					this.OnTagIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketStatus", DbType="Char(1)")]
		public System.Nullable<char> TicketStatus
		{
			get
			{
				return this._TicketStatus;
			}
			set
			{
				if ((this._TicketStatus != value))
				{
					this.OnTicketStatusChanging(value);
					this.SendPropertyChanging();
					this._TicketStatus = value;
					this.SendPropertyChanged("TicketStatus");
					this.OnTicketStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Char(1)")]
		public System.Nullable<char> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this.OnPhone_NumberChanging(value);
					this.SendPropertyChanging();
					this._Phone_Number = value;
					this.SendPropertyChanged("Phone_Number");
					this.OnPhone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assignee", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Assignee
		{
			get
			{
				return this._Assignee;
			}
			set
			{
				if ((this._Assignee != value))
				{
					this.OnAssigneeChanging(value);
					this.SendPropertyChanging();
					this._Assignee = value;
					this.SendPropertyChanged("Assignee");
					this.OnAssigneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalNotes", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string AdditionalNotes
		{
			get
			{
				return this._AdditionalNotes;
			}
			set
			{
				if ((this._AdditionalNotes != value))
				{
					this.OnAdditionalNotesChanging(value);
					this.SendPropertyChanging();
					this._AdditionalNotes = value;
					this.SendPropertyChanged("AdditionalNotes");
					this.OnAdditionalNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
